### ISSUE TITLE
Errors on `nvm use` - `Unknown command 'string' etc.

### ISSUE THREAD

**Issue by bradfx** [brigand/fast-nvm-fish#17]
I'm getting the below error from the latest `nvm.fish` function.
```
nvm use 9
fish: Unknown command 'string'
in command substitution
	called on line 0 of file ~/.config/fish/functions/nvm.fish

in function 'nvm-fast'
	called on line 44 of file ~/.config/fish/functions/nvm.fish
	with parameter list 'use 9'

in function 'nvm'
	called on standard input
	with parameter list 'use 9'

fish: Unknown command 'sed'
/usr/local/share/fish/functions/prompt_pwd.fish (line 2): 	echo $PWD | sed -e "s|^$realhome|~|" $args_pre -e 's-\([^/.]\)[^/]*/-\1/-g' $args_post
                                                          	            ^
in function 'prompt_pwd'
	called on line 6 of file /usr/local/share/fish/functions/fish_prompt.fish

in command substitution
	called on line 4 of file /usr/local/share/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```
I wasn't getting this error until I updated my `nvm.fish` function today.

I've tried reinstalling everything, from iTerm2, nvm, and nvm-fast-fish. I've had to roll back a few commits on `nvm.fish` and everything works fine :) Looks like a bug has been introduced.

**Comment by bradfx** [comment]
`nvm.fish` from commit 9000fb4d20d0abc48eac6e6364c90f449856bbd7 works fine :)

**Comment by bradfx** [comment]
Looks like we could use some unit tests, with all these new features coming in.

**Comment by brigand** [comment]
@bradleyflood it's saying `Unknown command 'sed'`. Are you on alpine linux or similar? The latest code is working for me on osx.

**Comment by bradfx** [comment]
Yeah I noticed that. I'm on OSX 10.13. Running `sed` in the command line works fine (including in fish shell).

**Comment by brigand** [comment]
@bradleyflood oh, that line of code isn't even in this plugin. It looks like an issue with your fish config. Perhaps you created a function with the same name as a command line program we use.

**Comment by bradfx** [comment]
@brigand Hmm. Well this is a completely fresh install. I've nuked the `~/.nvm` and `~/.config/fish/` folders multiple times trying to troubleshoot this.

**Comment by bradfx** [comment]
It looks like the error is happening whilst Fish is building the prompt. Now that I've set my prompt to the `Informative Git Prompt` I'm also getting `fish: Unknown command 'git'` errors.

**Comment by bradfx** [comment]
My `fish.config` file is literally just:
```
nvm use 9
```

**Comment by brigand** [comment]
@bradleyflood I'd guess your `PATH` is messed up somehow.

**Comment by bradfx** [comment]
Ok must be something on my machine. I'll look into it and report back. Thanks.
```
echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/git/bin
```

**Comment by bradfx** [comment]
The weird thing is that everything works fine with an older version of the `nvm.fish` function.

**Comment by bradfx** [comment]
Note, just for context, that when I said I get `Unknown command 'git'` error, I only get that error when I run `nvm use 9` with the latest `nvm.fish` function. Otherwise my prompt and git and everything else works fine. So it must be something in the `nvm.fish` code introduced in the last few months. I'll look into it.

**Comment by bradfx** [comment]
Ok well it's working fine on my work machine (MacBook) so it must be my machine. I'll look into it and report.

**Comment by tomsaleeba** [comment]
@bradleyflood what version of Fish are you using? It seems like the `string` builtin might've been added in https://github.com/fish-shell/fish-shell/commit/dfb499877863cc1e19b282b4ef358504807b97fc#diff-a3b6632775c9665e491e7386957e1cc4. Although it seems like that expects that `string` *may* already exist.

Anyway, assuming you don't have `string` and you're on Fish [2.3.1](https://github.com/fish-shell/fish-shell/releases/tag/2.3.1) that was released before that `string.fish` function was added, that would explain the error.

**Comment by bradfx** [comment]
I'm going to close this. I can't replicate it anymore.
