### ISSUE TITLE
Would be nice to have this on AUR

### ISSUE THREAD

**Issue by gunar** [brigand/fast-nvm-fish#19]
I've done it once, it's pretty straightforward actually. Can you do it? If not, would you mind?

**Comment by brigand** [comment]
So, I added a license with a note:

> This license was added Mar 27th 2018, and may not cover contributions by people other than Frankie Bagnardi.
> Copyright 2016-2018 Frankie Bagnardi \<f.bagnardi@gmail.com\> and contributors

It's up to you to decide if this is sufficient, and if you determine it is, then you may publish it however you like.

I haven't heard of AUR, so I'll let you work that out. Feel free to send a PR if you want something added to the readme.

**Comment by gunar** [comment]
I ended up not doing it because I realized I don't use fish (but zsh), and [this](https://github.com/creationix/nvm/issues/1277#issuecomment-356571440) solved my problem. Thanks.
