### ISSUE TITLE
No node version loaded when opening Terminal

### ISSUE THREAD

**Issue by jordyvandomselaar** [brigand/fast-nvm-fish#26]
When first opening my terminal both node and npm are unknown commands. I have to `nvm use <>` manually to get it to work.

Am I missing something?

**Comment by brigand** [comment]
From the readme:

> To make it work on new shells you'll need to set a version in config.fish.
> `echo 'nvm use 7.2.1' >> ~/.config/fish/config.fish`

**Comment by jordyvandomselaar** [comment]
I am very sorry. I missed that =(

**Comment by hughrawlinson** [comment]
I'm also encountering this issue. I saw the line in the readme. Why doesn't it use the nvm default? `nvm use` takes time every time I open a terminal, and nvm already has the 'default node' behaviour built in.

**Comment by brigand** [comment]
It provides a function, which you can call if/when you want to use it.

I don't like the idea of modifying `PATH` when you `source`/`fundle plugin` something. Maybe that's made up for by ease of use... I'm conflicted. Going to leave it as-is for now.
