### ISSUE TITLE
Mention that nvm must also be installed

### ISSUE THREAD

**Issue by bookercodes** [brigand/fast-nvm-fish#3]
Hi 👋 

I really like this tool, thank you, but the documentation could be much better. In particular, I think it would be useful to mention that [`nvm`](https://github.com/creationix/nvm) is still required for this tool to work.

I would also mention the `set -U fish_user_paths` command higher up in the document because it's the first thing that needs to be run.

Again, thank you.

**Comment by brigand** [comment]
Added the note about nvm.sh needing to be installed.

I think the order in the readme is fine. The readme is short enough that I can expect people will read it all.
