### ISSUE TITLE
.nvmrc support for `nvm use`

### ISSUE THREAD

**Issue by piotrwitek** [brigand/fast-nvm-fish#7]
when invoking `nvm use` with `.nvmrc` got the following error:
```bash
> nvm use                                                                         13:53:05
Array index out of bounds
~/.config/fish/functions/nvm.fish (line 9): 		set -l target_version $argv[2]
                                            		                            ^
in function 'nvm-fast'
	called on line 98 of file ~/.config/fish/functions/nvm.fish
	with parameter list 'use'

in function 'nvm'
	called on standard input
	with parameter list 'use'

No version installed for , run nvm install
Installed versions:
 - /Users/piotrek/.nvm/versions/node/v6.10.2
 - /Users/piotrek/.nvm/versions/node/v7.9.0
```

- `.nvmrc` file contents
```
6.10.2
```

reference: https://github.com/creationix/nvm#nvmrc

**Comment by corysimmons** [comment]
He's actually maintaining but just ignoring this issue (i.e. the entire reason nvm is useful). :^)

**Comment by brigand** [comment]
@corysimmons a more productive comment would have been "Hey, could this be done now?", but instead you decided to assume bad intent and call the project useless.

I don't remember seeing this issue before now. It seems like a fine thing to support, but I have less interest in doing open source when people are rude.

If you would like to make this project "useful", please send a PR.

**Comment by corysimmons** [comment]
I never rly thought of it like that🤔💭 .
